name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 1.5: Verificar archivos en el runner
      - name: List files
        run: ls -la

      # Paso 2: Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Ejecutar tests
      - name: Run tests
        run: npm test

      # Paso 5 (opcional): Iniciar servidor
      # - name: Start server
      #   run: npm run dev
